### ISSUE TITLE
Problem mit der Maven installation 

### ISSUE THREAD

**Issue by NikMass** [Cryxnoob/TeamProjectTH-BingenEP-3#18]
![bildschirmfoto 2017-10-17 um 12 39 49](https://user-images.githubusercontent.com/27808995/31660693-7f683978-b338-11e7-99d0-7dfce62bc188.jpg)

@nicolaiparlog 

Ich habe ebenfalls Maven manuell runtergeladen und versucht über das Terminal zu installieren habe jetzt nach mehreren Stunden aufgegeben....

**Comment by NikMass** [comment]
Habe es hinbekommen, td vielen Danke!

**Comment by nicolaiparlog** [comment]
Wollte gerade schrieben, dass die Fehlermeldung nahelegt, dass Jenv gerade nicht verfügbar ist. Wenn es jetzt funktioniert hat, ist ja alles in Ordnung. Kann das Ticket dann geschlossen werden?
