### ISSUE TITLE
Simulation wird besser konfiguriert 

### ISSUE THREAD

**Issue by bene1909** [Cryxnoob/TeamProjectTH-BingenEP-3#34]
Anzahl und Kapazität der Segmente konfigurierbar machen. Die Werte müssen auch von der CSV analysiert werden. Dazu Scenario und External Funktionen entsprechend updaten.
Das Netzwerk soll die verbleibende und die gesamte Kapazität der Segmente verfolgen und die Ergebnisse in die Konsole oder CSV schreiben.
In jedem Segment verzögern nur die Züge, die die Kapazität überlaste.
Welch Züge auf einem Segment verzögert werden, soll nach dem Zufallsprinzip entschieden werden.
Jeder Zug soll mit gleicher Wahrscheinlichkeit verspätet werden.
Die Readme soll durch eine Benutzerdokumentation erweitert werden.

**Comment by nicolaiparlog** [comment]
Die ganze Aufgabe in einem Issue zu erledigen ist nicht allzu geschickt. Einige der Aufgaben können unabhängig voneinander und somit parallel von verschiedenen Personen bearbeitet werden.

**Comment by espe2** [comment]
Wir haben die Aufgabe ja aufgeteilt und es wurde von mehren Personen bearbeitet

**Comment by nicolaiparlog** [comment]
Das mag sein, aber Issues dienen dazu einzelne Arbeitspunkte festzuhalten und ihren Fortschritt nachzuvollziehen, was bei "echten" Projekten absolut überlebensnotwendig ist. Mit der Herangehensweise "Schreib ein Programm, das mein Problem löst" kommt man nicht weit und deswegen sollt ihr ja lernen, Aufgaben sinnvoll zu trennen (wobei die Bullet Points da schon eine gute Vorgabe machen) und getrennt zu bearbeiten.

Alle Aufgaben eines Meilensteins in einem Issue und einem PR zu lösen ist auf jeden Fall keine sinnvolle Herangehensweise und führt zu (kleinen) Abzügen in der B-Note.
