### ISSUE TITLE
Fehler in Randomisierung beheben

### ISSUE THREAD

**Issue by nicolaiparlog** [Cryxnoob/TeamProjectTH-BingenEP-3#36]
Der folgende Code bestimmt welche Züge verspätet sind:

    for (segment in segments){
        if (segment.getcurrentcount()>segment.capacity){

            diff = segment.getcurrentcount()-segment.capacity
            x = diff
            while (x > 0 ){
                delayedtrains.add(Random().nextInt(segment.getcurrentcount()))
                x--
            }
            y = 0

            for (train in trains){
                if (train.getcurrentSegment(currentstep)==segment.id){
                    for (delayedtrain in delayedtrains){
                        if (delayedtrain == y){
                            train.setDelayed(true)
                        }
                    }
                    y++
                }
            }
        }
    }

Die Lösung ist fehlerhaft. Mit `delayedtrains.add(Random().nextInt(segment.getcurrentcount()))` kann die gleiche Zahl mehrfach eingefügt werden, was dazu führen würde, dass der gleiche Zug "mehrfach verspätet" ist, was natürlich keinen Unterschied macht.

**Comment by nicolaiparlog** [comment]
Wenn ihr dies hier und [diesen Kommentar](https://github.com/Cryxnoob/TeamProjectTH-BingenEP-3/pull/35#issuecomment-341361266) bearbeitet habt, müsst ihr mit den Ausbesserungen noch 3.1 releasen.

**Comment by NikMass** [comment]
Sie haben gestern auf unsere Anfrage geantwortet aber nicht auf unser Projekt. Da heute um 18:00 Abgabe ist und sie  nichts bemängelt haben und sagten, dass wenn Travis grünes Licht
gibt wir mergen dürfen, haben wir folglich diesen PR als abgeschlossen und vollständig angesehen und somit gemerged.
Am 02.11.2017 um 10:15 schrieb Nicolai Parlog <notifications@github.com<mailto:notifications@github.com>>:


Der folgende Code bestimmt welche Züge verspätet sind:

for (segment in segments){
    if (segment.getcurrentcount()>segment.capacity){

        diff = segment.getcurrentcount()-segment.capacity
        x = diff
        while (x > 0 ){
            delayedtrains.add(Random().nextInt(segment.getcurrentcount()))
            x--
        }
        y = 0

        for (train in trains){
            if (train.getcurrentSegment(currentstep)==segment.id){
                for (delayedtrain in delayedtrains){
                    if (delayedtrain == y){
                        train.setDelayed(true)
                    }
                }
                y++
            }
        }
    }
}


Die Lösung ist fehlerhaft. Mit delayedtrains.add(Random().nextInt(segment.getcurrentcount())) kann die gleiche Zahl mehrfach eingefügt werden, was dazu führen würde, dass der gleiche Zug "mehrfach verspätet" ist, was natürlich keinen Unterschied macht.

**Comment by nicolaiparlog** [comment]
Das ist auch alles in Ordnung so, aber ich wollte euch dennoch vor Bewertung eures Projekts darauf hinweisen, dass ein Fehler drin ist. Den kann man ja auch außerhalb dieses PRs noch lösen indem man ein neues Issue dazu anlegt und das dann bearbeitet.

**Comment by NikMass** [comment]
wurde bearbeitet
